steps:

### Build
  - id: 'build'
    name: 'gcr.io/cloud_builders/docker'
    dir: 'microservices/backend'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
          [[ "$BRANCH_NAME" ]] && VERSION=${BRANCH_NAME}-${SHORT_SHA}
          [[ "$TAG_NAME" ]] && VERSION=$TAG_NAME
          docker build -t gcr.io/${PROJECT_ID}/cloud_build/backend:$${VERSION} .


### Test


### Publish
  - id: 'publish'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
          [[ "$BRANCH_NAME" ]] && VERSION=${BRANCH_NAME}-${SHORT_SHA}
          [[ "$TAG_NAME" ]] && VERSION=$TAG_NAME
          docker push gcr.io/${PROJECT_ID}/cloud_build/backend:$${VERSION}


### Deploy
  - id: 'deploy'
    name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: bash
    env:
      - 'KUBECONFIG=/kube/config'
    args:
      - '-c'
      - |
          [[ "$BRANCH_NAME" ]] && VERSION=${BRANCH_NAME}-${SHORT_SHA}
          [[ "$TAG_NAME" ]] && VERSION=$TAG_NAME
          IMAGE_NAME=gcr.io/${PROJECT_ID}/cloud_build/backend:$${VERSION}
      
          if [[ "$TAG_NAME" ]] ; then
            TARGET_ENV=prod
            CLUSTER_NAME=$_CLUSTER_PROD
          elif [[ ${BRANCH_NAME} == "master" ]] ; then
            TARGET_ENV=canary; 
            CLUSTER_NAME=$_CLUSTER_PROD
          else 
            TARGET_ENV=dev; 
            CLUSTER_NAME=$_CLUSTER_DEV
          fi
          
          gcloud container clusters get-credentials $${CLUSTER_NAME} --zone=$_ZONE
          
          sed -i "s#_IMAGE_NAME#$${IMAGE_NAME}#g" $${MANIFEST_PATH}/deployments/$${TARGET_ENV}/*.yaml
          kubectl apply --recursive -f kubernetes/backend/deployments/$${TARGET_ENV}/*.yaml



### Prepare deploy
#   - id: 'prepare deploy'
#     name: 'gcr.io/cloud-builders/gke-deploy'
#     args:
#       - 'prepare'
#       - '--filename=kubernetes/backend/deployments/${BRANCH_NAME}'
#       - '--image=gcr.io/${PROJECT_ID}/cloud_build/${BRANCH_NAME}/backend:${BRANCH_NAME}-${SHORT_SHA}'
#       - '--output=gs://bucketconfig-01/'

# ### Deploy
#   - name: 'gcr.io/cloud-builders/gke-deploy'
#     id: 'Apply deploy'
#     args:
#     - 'apply'
#     - '--filename=gs://bucketconfig-01/expanded/*'
#     - '--cluster=models-cluster-dev'
#     - '--location=europe-west3-a'

substitutions:
  _ZONE: europe-west3-a
  _CLUSTER_PROD: standard-cluster-1
  _CLUSTER_DEV: models-cluster-dev