steps:


### Build
  - id: 'build'
    name: 'gcr.io/cloud_builders/docker'
    dir: 'microservices/backend'
    entrypoint: 'bash'
    args: ["docker", "build", "-t", "gcr.io/$PROJECT_ID/cloud_build/${BRANCH_NAME}/backend:${BRANCH_NAME}-${SHORT_SHA}", "."]


### Test


### Publish
  - id: 'publish'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ["docker", "push", "gcr.io/$PROJECT_ID/cloud_build/${BRANCH_NAME}/backend:${BRANCH_NAME}-${SHORT_SHA}"]


### Deploy