steps:


### Build
  - id: 'build'
    name: 'gcr.io/cloud_builders/docker'
    dir: 'microservices/backend'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
          VERSION=$BRANCH_NAME-$SHORT_SHA
          if [[ ${BRANCH_NAME} == "master" ]] ; then BRANCH=prod; else BRANCH=dev; fi
          docker build -t gcr.io/${PROJECT_ID}/cloud_build/$${BRANCH}/backend:$${VERSION} .


### Test


### Publish
  - id: 'publish'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
          VERSION=$BRANCH_NAME-$SHORT_SHA
          if [[ ${BRANCH_NAME} == "master" ]]; then BRANCH=master; else BRANCH=dev; fi
          docker push gcr.io/${PROJECT_ID}/cloud_build/$${BRANCH}/backend:$${VERSION}


### Deploy
  - id: 'deploy'
    name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: bash
    args:
      - '-c'
      - |
          if [[ ${BRANCH_NAME} == "master" ]]; then
            CLUSTER_NAME=$CLUSTER_PROD
            BRANCH=prod; 
          else 
            CLUSTER_NAME=$CLUSTER_DEV
            BRANCH=dev; 
          fi
          MANIFEST_PATH=kubernetes/backend
          IMAGE_NAME=gcr.io/${PROJECT_ID}/cloud_build/$${BRANCH}/backend:$BRANCH_NAME-$SHORT_SHA

          gcloud container clusters get-credentials $${CLUSTER_NAME} --zone=$ZONE
          
          sed -i "s#_IMAGE_NAME#$${IMAGE_NAME}#g" $${MANIFEST_PATH}/deployments/$${BRANCH}/*.yaml
          echo ""
          kubectl apply -f $${MANIFEST_PATH}/deployments/$${BRANCH}/*.yaml



### Prepare deploy
#   - id: 'prepare deploy'
#     name: 'gcr.io/cloud-builders/gke-deploy'
#     args:
#       - 'prepare'
#       - '--filename=kubernetes/backend/deployments/${BRANCH_NAME}'
#       - '--image=gcr.io/${PROJECT_ID}/cloud_build/${BRANCH_NAME}/backend:${BRANCH_NAME}-${SHORT_SHA}'
#       - '--output=gs://bucketconfig-01/'

# ### Deploy
#   - name: 'gcr.io/cloud-builders/gke-deploy'
#     id: 'Apply deploy'
#     args:
#     - 'apply'
#     - '--filename=gs://bucketconfig-01/expanded/*'
#     - '--cluster=models-cluster-dev'
#     - '--location=europe-west3-a'

# images:
# - '$_IMAGE_NAME:$_IMAGE_VERSION'

# substitutions:
#   _DOCKERFILE_PATH: Dockerfile
#   _IMAGE_NAME:
#   _IMAGE_VERSION:
#   _GKE_CLUSTER:
#   _GKE_LOCATION:
#   _K8S_YAML_PATH:
#   _K8S_APP_NAME:
#   _K8S_NAMESPACE:
#   _OUTPUT_BUCKET_PATH:

# options:
#   substitution_option: 'ALLOW_LOOSE'

# tags: [$_K8S_APP_NAME']