steps:

### Build
  - id: 'build'
    name: 'gcr.io/cloud_builders/docker'
    entrypoint: 'bash' 
    args: 
      - '-c'
      - |
          [[ "$BRANCH_NAME" ]] && VERSION=${BRANCH_NAME}-${SHORT_SHA}
          [[ "$TAG_NAME" ]] && VERSION=$TAG_NAME
          docker build -t gcr.io/$PROJECT_ID/cloud_build/dev/backend:$${VERSION} .


### Test


### Publish
  - id: 'publish'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
          [[ "$BRANCH_NAME" ]] && VERSION=${BRANCH_NAME}-${SHORT_SHA}
          [[ "$TAG_NAME" ]] && VERSION=$TAG_NAME
          docker push gcr.io/$PROJECT_ID/cloud_build/dev/backend:$${VERSION} .


### Deploy
