steps:


### Build
  - id: 'build'
    name: 'gcr.io/cloud_builders/docker'
    dir: 'microservices/backend'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
          VERSION=$BRANCH_NAME-$SHORT_SHA
          BRANCH=${if [[ ${BRANCH_NAME} == "master" ]] ; then "master"; else "dev"; fi}
          docker build -t gcr.io/$PROJECT_ID/cloud_build/$BRANCH/backend:$${VERSION} .


### Test


### Publish
  - id: 'publish'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
          VERSION=$BRANCH_NAME-$SHORT_SHA
          BRANCH=${if [[ ${BRANCH_NAME} == "master" ]] ; then "master"; else "dev"; fi}
          docker push gcr.io/$PROJECT_ID/cloud_build/$BRANCH/backend:$${VERSION}


### Prepare deploy


### Deploy