apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudbuildbackend-prod
spec:
  selector:
    matchLabels:
      app: cloudbuild
  replicas: 3
  template:
    metadata:
      labels:
        app: cloudbuild
        role: backend
        env: prod
    spec:
      containers:
      - name: backend
        image: _IMAGE_NAME
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - containerPort: 5000