apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud_build-backend-dev
spec:
  selector:
    matchLabels:
      app: cloud_build
  replicas: 2
  template:
    metadata:
      labels:
        app: cloud_build
        role: backend
        env: dev
    spec:
      containers:
      - name: backend
        image: _IMAGE_NAME
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - containerPort: 5000